<?php
/*
 * This is a Views endpoint module for AJAX use.
 * This module is inspired by Communications module and Campus Management module
 * made and partially made by Shawn Arsenault. I feel sure that we should use a
 * general view for AJAX endpoint instead of building modules for each type we
 * need in the future.
 *
 * We just need to use JQuery to load the content or PHP code file_get_contents
 * to get the endpoint in the future.
 *
 * This module is released under GPL v3. Please refer to GPL's website for
 * licensing information. <http://www.gnu.org/copyleft/gpl.html>
 *
 * Yuxing Huang, TFDC <yxh@twofathomsdeep.com> and
 *   University of Prince Edward Island
 *
 */

function views_ajax_endpoint_views_api() {
  return array('api' => 2);
}

function views_ajax_endpoint_footer($main = 0) {
  $content = '';
  $path = base_path() . drupal_get_path('module', 'views_ajax_endpoint')  . '/codemirror';
  $q = $_REQUEST['q'];
  if (preg_match('|^admin/build/views|', $q)) {
    $content .= <<<EOL
<script type="text/javascript" src="$path/js/codemirror.js"></script>
EOL;
  }
  
  return $content;
}

function views_ajax_endpoint_field_formatter_info() {
  $formatters = array();
  if (module_exists('filefield')) {
    $formatters['url_raw'] = array(
      'label' => t('Raw URL to file'),
      'field types' => array('filefield', 'image'),
      'multiple values' => CONTENT_HANDLE_CORE,
    );
    $formatters['path_raw'] = array(
      'label' => t('Raw path to file'),
      'field types' => array('filefield', 'image'),
      'multiple values' => CONTENT_HANDLE_CORE,
    );
  }
  return $formatters;
}

function theme_views_ajax_endpoint_formatter_url_raw($element) {
  if (empty($element['#item'])) {
    return '';
  }
  
  $item = $element['#item'];
  $original_image_url = file_create_url($item['filepath']);
  
  return $original_image_url;
}

function theme_views_ajax_endpoint_formatter_path_raw($element) {
  if (empty($element['#item'])) {
    return '';
  }
  
  $item = $element['#item'];
  return $item['filepath'];
}

function views_ajax_endpoint_theme($existing, $type, $theme, $path) {
  return array(
    'views_ajax_endpoint_formatter_url_raw' => array(
      'arguments' => array('element' => NULL),
      ),
    'views_ajax_endpoint_formatter_path_raw' => array(
      'arguments' => array('element' => NULL),
      )
    );
}