<?php
// $Id: image_import.module,v 1.17 2008/06/16 18:30:10 drewish Exp $

/**
 * Implementation of hook_help().
 */
function image_import_help($path, $arg) {
  switch ($path) {
    case 'admin/content/image_import':
      $output = '<p>'. t("Import multiple image files and save them as image nodes. The files will be moved from their location into the image module's files directory. ")
        . t("Searching for image files in %dirpath.", array('%dirpath' => realpath(variable_get('image_import_path', '')))) .'</p>';
      return $output;
    case 'admin/settings/image_import':
      return t("Configure the image import module's settings.");
    default:
      return null;
  }
}

/**
 * Implementation of hook_perm().
 */
function image_import_perm() {
  return array('import images');
}

/**
 * Implementation of hook_menu().
 */
function image_import_menu() {
  $items = array();
  
  $items['admin/content/image_import'] = array(
    'title' => 'Image import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('image_import_form'),
    'file' => 'image_import.admin.inc',
    'access arguments' => array('import images'),
    'type' => MENU_NORMAL_ITEM,
    'description' => 'Import images from the filesystem.',
  
  );
  $items['admin/settings/image/image_import'] = array(
    'title' => 'Image import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('image_import_admin_settings'),
    'file' => 'image_import.admin.inc',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'description' => 'Change settings for the Image Import module.',
  );

  return $items;
}

/**
 * Implementation of hook_theme() registry.
 **/
function image_import_theme() {
  return array(
    'image_import_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'image_import.admin.inc',
    ),
  );
}

