<?php
// $Id: imagecache_textactions.module,v 1.2.2.6 2009/02/07 16:31:19 dman Exp $
/**
 * @file Provide text manipulation process for imagecache.
 * 
 * Ported by dman 
 * from http://drupal.org/node/264862#comment-865490 by patrickharris
 * 
 */

require_once(dirname(__FILE__) .'/utility.inc'); // For simple color routines

/**
* Implementation of hook_imagecache_actions().
*/ 
function imagecache_textactions_imagecache_actions() {
  $actions = array(
    'textactions_text2canvas' => array(
      'name' => t('Text'),
      'description' => t('Add static or dynamic (coded) text to an image.'),
      'file' => 'textactions.inc',
    ),
  );

  return $actions;
}

/**
 * Experimental diagnostic page to assist locating valid fonts on the system.
 * Only tuned for Ubuntu so far. I've been unable do find ubiquitous tools that
 * provide useful font listings.'
 */
function imagecache_textactions_help($path, $arg) {
  switch ($path) {
    case 'admin/help#imagecache_textactions':
      if( ini_get('safe_mode') ){
        return t("
          It appears PHP 'safe mode' is on. 
          This prevents me for knowing which fonts are on your system. 
          You will have to know the exact path and filename of the fonts you intend to use 
          - or upload some *.ttf files to your 'files' directory and use them from there.
        ");
      }
      else {
        $output = `find /usr/share/fonts -name \*.ttf`;
        return "Fonts Found : <pre>" . $output . "</pre>";
      }
  }
}

/**
 * Need to register the theme functions we expect to use
 */
function imagecache_textactions_theme() {
  return array(
    'textactions_text2canvas' => array(
      'file'      => 'textactions.inc',
      'arguments' => array('element' => NULL),
    ),
    'imagecacheactions_rgb_form' => array(
      'file'      => 'utility.inc',
      'arguments' => array('form' => NULL),
    ),
    'imagecacheactions_rgb' => array(
      'file'      => 'utility.inc',
      'arguments' => array('rgb' => NULL),
    ),
  );
}